name: Checkout a repo into current $GITHUB_WORKSPACE
on:
  push:
jobs:

  checkout-display-files:
    runs-on: ubuntu-latest
    steps:

      - name: List Files Before
        run: ls -a

      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main

      - name: List Files After
        run: ls -a

  checkout-with-action:
    runs-on: ubuntu-latest
    steps:

      - name: List Files Before
        run: ls -a

      - name: Checkout repo using the checkout action
        uses: actions/checkout@v3

      - name: List Files After
        run: ls -a
