name: Concurrency 1
run-name: On ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
