name: Docker
on:
  workflow_dispatch:
jobs:

  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
      # credentials:
      #   username:
      #   password:
      # volumes:
      #   - vol_name:/path/in/container
      #   - path/to/container
      #   - /path/in/host:/path/in/container
      # options: --cpus 1
    steps:

      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release

      - name: Echo env var
        run: |
          echo $API_URL

      - name: Create file to prove files are carried across containers within job
        run: |
          echo 'some text' > file_in_job_container.txt

      - name: Container in a steps
        uses: docker://node:18.19-alpine
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3

      - name: Container in a steps
        uses: docker://node:18.19-alpine
        with:
          # entrypoint: /usr/local/bin/node  ## By default the node container has entrypoint of node
          args: -v

      - name: Display file contents of file_in_job_container.txt
        uses: docker://node:18.19-alpine
        with:
          entrypoint: cat
          args: file_in_job_container.txt

      - name: Checkout local repo to get access to script
        uses: actions/checkout@v3

      - run: cat $GITHUB_WORKSPACE/script.sh

      - name: Use script in docker container entrypoint
        uses: docker://node:18.19-alpine
        with:
          entrypoint: "${GITHUB_WORKSPACE}/script.sh"
          # entrypoint: ./script.sh
          args: "Some string"
