name: Docker
on:
  workflow_dispatch:
jobs:

  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
      # credentials:
      #   username:
      #   password:
      # volumes:
      #   - vol_name:/path/in/container
      #   - path/to/container
      #   - /path/in/host:/path/in/container
      # options: --cpus 1
    steps:

      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release

      - name: Echo env var
        run: |
          echo $API_URL

      - name: Container in a steps
        uses: docker://node:18.19-apline
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3

      - name: Container in a steps
        uses: docker://node:18.19-apline
        with:
          # entrypoint: /usr/local/bin/node  ## By default the node container has entrypoint of node
          args: -v
