name: Expressions and Contexts
run-name: "Expressions and Contexts by @${{ github.actor }} event:${{ github.event_name }}"
on:
  push:
  pull_request:
  issues:
  workflow_dispatch:
jobs:

  only-run-issues-pr:
    runs-on: ubuntu-latest
    if: contains(fromJson('["issues", "pull_request"]'), github.event_name)  ## Is checking if github.event_name is in the array including 'issues' and 'pull_request'
    steps:

      - name: Echo something if issue has bug label
        if: contains('bug', github.event.issue.labels.*.name)
        run: |
          echo ${{ join(github.event.issue.labels.*.name) }}

  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:

      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'Hello, world!' }}
          echo ${{ null }}
          echo ${{ false }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}

      - name: Dump Contexts
        run: |
          echo "github context ${{ github }}"
          echo "job context ${{ toJson(job) }}"
          echo "secrets context ${{ toJson(secrets) }}"
          echo "steps context ${{ toJson(steps) }}"
          echo "runner context ${{ toJson(runner) }}"
