name: Expressions and Contexts
run-name: "Expressions and Contexts by @${{ github.actor }} event:${{ github.event_name }}"
on:
  push:
  pull_request:
  issues:
  workflow_dispatch:
jobs:

  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:

      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'Hello, world!' }}
          echo ${{ null }}
          echo ${{ false }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}

      - name: Dump Contexts
        run: |
          echo "github context ${{ github }}"
          echo "job context ${{ toJson(job) }}"
          echo "secrets context ${{ toJson(secrets) }}"
          echo "steps context ${{ toJson(steps) }}"
          echo "runner context ${{ toJson(runner) }}"
