name: Matrix
on:
  push:
jobs:

  node-matrix:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [13,14,15]
        os: [ubuntu-latest,windows-latest]
        include:
          - os: ubuntu-latest
            is-ubuntu: tue
          - os: macos-latest
            node-version: 16
          - experimental: false
          - os: ubuntu-latest
            node-version: 13
            experimental: true
        exclude:
          - os: ubuntu-latest
            node-version: 15
    steps:

      - name: Fail experimental matrix
        if: matrix.experimental == true
        run: |
          echo ls -&%

      - name: echo out the matrix
        run: |
          echo '${{ toJson(matrix) }}'

      - name: output the pre node version
        run: node -v

      - name: set up node using matrix
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: output the post node version
        run: node -v
