name: Matrix
on:
  push:
jobs:

  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13,14,15,16]
    steps:

      - name: output the pre node version
        run: node -v

      - name: set up node using matrix
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: output the post node version
        run: node -v
