name: Work with scheduled triggers and the stale action
on:
  schedule:
    - cron: "40 3 * * *"
jobs:

  stale:
    runs-on: ubuntu-latest
    steps:

      - name: Run action on stale issues and PR
        uses: actions/stale@v8
        with:
          stale-issue-message: "This is stale"
          days-before-stale: 1
          days-before-close: 5
