name: Check for status of jobs
on:
  push:
jobs:

  job-1:
    runs-on: ubuntu-latest
    steps:

      - name: step 1 -- sleep for 20
        run: sleep 20

      - name: step 2 -- failure
        id: step-2
        run: ls -%

      - name: always run on failure
        if: failure()
        run: echo "I always run on failure"

      - name: run on failure for only step-2
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo "I ran on failure for step-2"

      - name: run on success
        if: success()  ## default behavior, not needed for something so simple like this step
        run: echo "I ran on success (which is also the default behavior..no need to define if conditional)"

      - name: run always
        if: always()
        run: echo "I always run"

      - name: runs when cancelled
        if: cancelled()
        run: echo "I run when cancelled"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    if: failure()
    steps:

      - name: run on failure
        run: echo "I ran on failure of job-1"
