name: Calling reusable workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'a name'
        type: string
        default: 'Bob'
        required: true
jobs:

  calling-reusable-wf-external:
    uses: slammin/gh_workflows_ali_1/.github/workflows/reusable.yaml@main
    with:
      name: '${{ inputs.name }}'
    secrets:
      access-token: '${{ secrets.GH_TOKEN }}'

  calling-reusable-wf-internal:
    permissions:
      issues: read
    uses: ./.github/workflows/reuse-wf.yaml
    secrets: inherit
      # access-token: '${{ secrets.GH_TOKEN }}'

  uses-reusuable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-reusable-wf-internal
    steps:

      - run: |
          echo ${{ needs.calling-reusable-wf-internal.outputs.date }}
          echo ${{ needs.calling-reusable-wf-internal.outputs.year }}
