name: work with vars and secrets and environments
on:
  push:
jobs:

  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo to get access to file
        uses: actions/checkout@v3

      - name: decrypt file
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSWORD }}" --output $HOME/secrets/secret.json ../secret.json.gpg

      - name: view decrypted file
        run: |
          cat $HOME/secrets/secret.json

  job-2:
    environment: staging
    runs-on: ${{ vars.JOB_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:

      - name: output what env you are in
        run: |
          echo "job context ${{ toJson(github) }}"
          echo ${{ github.job.environment.name }}

      - name: output all vars
        run: |
          echo "BOOLEAN_SECRET is: $BOOLEAN_SECRET"
          echo $ENV_LEVEL_VAR
          echo "REPO_LEVEL_VAR is: $REPO_LEVELVAR"

      - name: run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: |
          echo "BOOLEAN_SECRET was true"
