name: work with vars and secrets and environments
on:
  push:
jobs:

  job-1:
    environment: production
    runs-on: ${{ vars.JOB_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:

      - name: output what env you are in
        run: |
          echo "job context ${{ toJson(github) }}"
          echo ${{ github.jobs.environment.name }}

      - name: output all vars
        run: |
          echo "BOOLEAN_SECRET is: $BOOLEAN_SECRET"
          echo $ENV_LEVEL_VAR
          echo "REPO_LEVEL_VAR is: $REPO_LEVELVAR"

      - name: run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: |
          echo "BOOLEAN_SECRET was true"
